### ISSUE TITLE
Bayesian Network Structure

### ISSUE THREAD

**Issue by NazimR** [ITMO-NSS-team/BAMT#26]
Hi again,

I have two questions?

1. How to draw network structure manually for HBN?

encoder = preprocessing.LabelEncoder()
discretizer = preprocessing.KBinsDiscretizer(n_bins=5, encode='ordinal', strategy='quantile')
p = pp.Preprocessor([('discretizer', discretizer)])
discretized_data, est = p.apply(TrainingSet)

edges = [('sepalL', 'target'), ('sepalW', 'target'), ('petalL', 'target'),  ('petalW', 'target')]
bn = Nets.HybridBN(has_logit=True, use_mixture=True) 
info = p.info
TrainingSet.info()
bn.add_nodes(info)
bn.set_structure(edges)
bn.get_info()

I try write the code but doesn't work. All the variables do not link accordingly to what I want.

2.  bn.plot('Simple.html') not working, the output return "Local cdn resources have problems on chrome/safari when used in jupyter-notebook." 

I really appreciate your help. Thank you :)

**Comment by Roman223** [comment]
Hello NazimirR,

 "Local cdn resources have problems on chrome/safari when used in jupyter-notebook." is a warning, it does not crush your plot. The reason is about setting your structure. I suppose, output of `bn.get_info()` appears without edges.<br>
```
    def set_structure(self,
                      info: Optional[Dict] = None,
                      nodes: Optional[List] = None,
                      edges: Optional[List[Sequence[str]]] = None,
                      overwrite: bool = True): <...>
``` 
`bn.set_structure(...)` accepts keyword arguments, that is if you pass a positional one, the interpreter will see the following: `bn.set_structure(info=edges)`.

**Comment by NazimR** [comment]
Thank you for your help and explanation. I'm successfully solved them :).

 bn.set_structure(...) suppose to be  bn.set_structure(edges = edges) in order to pass my edges = [('sepalL', 'target'), ('sepalW', 'target'), ('petalL', 'target'), ('petalW', 'target')].
